import os
import json
from openai import OpenAI

# Initialize the client
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY", "<OPENAI_API_TOKEN>"))

# Define the "Tools" (Function Definitions)
# This schema tells the model what the function 'get_weather' does
function_definition = [
    {
        "type": "function",
        "function": {
            "name": "get_weather",
            "description": "Get the current weather in a given location",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The city and state, e.g. San Francisco, CA",
                    },
                    "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                },
                "required": ["location"],
            },
        },
    }
]

# Define the messages
message_listing = [{"role": "user", "content": "What's the weather like in Paris?"}]

# Create the request
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=message_listing,
    tools=function_definition,
    tool_choice="auto"  # The model decides if it needs a tool
)

# Extract and print the tool call arguments
# Note: 'tool_calls' is a list because the model can call multiple functions at once
tool_call = response.choices[0].message.tool_calls[0]
arguments = json.loads(tool_call.function.arguments)

print(f"Function to call: {tool_call.function.name}")
print(f"Arguments generated by AI: {arguments}")



# Define the function to extract the data dictionary
def extract_dictionary(response):
  return response.choices[0].message.tool_calls[0].function.arguments

# Print the data dictionary
print(extract_dictionary(response))